/* Populate tabla clientes */
INSERT INTO usuario (NOMBRE_USUARIO, USUARIO, CONTRASENA, ROL, CORREO) VALUES('ADMINISTRADOR', 'administrador', '12345', 'ADM', 'prueba@hotmail.com');
INSERT INTO usuario (NOMBRE_USUARIO, USUARIO, CONTRASENA, ROL, CORREO) VALUES('USUARIO', 'usuario', '12345', 'USU', 'prueba1@hotmail.com');

INSERT INTO FORMULARIO (NOMBRE_FORMULARIO) values ('FORMULARIO1');
INSERT INTO FORMULARIO (NOMBRE_FORMULARIO) values ('FORMULARIO2');

INSERT INTO PREGUNTA (NOMBRE_PREGUNTA, ID_FORMULARIO) VALUES ('PREGUNTA1',1);
INSERT INTO PREGUNTA (NOMBRE_PREGUNTA, ID_FORMULARIO) VALUES ('PREGUNTA2', 1);
INSERT INTO PREGUNTA (NOMBRE_PREGUNTA, ID_FORMULARIO) VALUES ('PREGUNTA1', 2);
INSERT INTO PREGUNTA (NOMBRE_PREGUNTA, ID_FORMULARIO) VALUES ('PREGUNTA2',2);

INSERT INTO OPCION (DESCRIPCION_OPCION, ID_PREGUNTA) VALUES ('OPCION1',1);
INSERT INTO OPCION (DESCRIPCION_OPCION, ID_PREGUNTA) VALUES ('OPCION2', 1);
INSERT INTO OPCION (DESCRIPCION_OPCION, ID_PREGUNTA) VALUES ('OPCION1', 2);
INSERT INTO OPCION (DESCRIPCION_OPCION, ID_PREGUNTA) VALUES ('OPCION2',3);

INSERT INTO FORMULARIO_USUARIO (ID_FORMULARIO, ID_OPCION_PREGUNTA,ID_PREGUNTA,ID_USUARIO) VALUES (1,1,1,2);

INSERT INTO FORMULARIO_USUARIO (ID_FORMULARIO, ID_OPCION_PREGUNTA,ID_PREGUNTA,ID_USUARIO) VALUES (2,4,3,2);